# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7aa4b97bd1c1b480075ef0cbaf3880db8fc5a9914fc5c69df47312ac65d07f02898fda0ff7086e87d2f9b0baf956d06119a5c62cc45a231246d10f391cc109b

test:
  secret_key_base: 6fe3b8be496f2f11ccf521d5d042194fbe3295e0915c7a13dbba100f351f94c9c869423eba92f888984e86a9c6491c88e6a85867103ec4e20667a0143b3c82bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
